.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Kunzol
.\"
.TH MTVCLIENT 1 "Juli 10 2021"
.SH NAME
mtvclient \- Starter fuer mtv_cli.py
.SH SYNOPSIS
.B mtvclient 
.RI [ -A | --akt ] 
.RI [ -V | --vormerken ] 
.RI [ -S | --sofort ] 
.RI [ -E | --edit ] 
.RI [ -D | --download ] 
.RI [ -Q | --query ] 
.RI [ -b | --batch ] 
.RI [ -d | --db ] 
.RI [ -q | --quiet ] 
.RI [ -l | --level ] 
.RI [ -v | --version ] 
.RI [ -h | --hilfe ] 
.RI [ suche ] 
.SH DESCRIPTION
Kommandozeilen Programm für MediathekView
.SH OPTIONS
.B \-h, \-\-hilfe
Uebersicht der Parameter.
.TP
.B \-v, \-\-version
Version des Programms.
.SH SEE ALSO
.BR /usr/lib/mtvclient/bin/mtv_cli.py.
