.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 Kunzol
.\"
.TH MTVWEB 1 "Juli 10 2021"
.SH NAME
mtvclient \- Starter fuer mtv_web.py
.SH SYNOPSIS
.B mtvweb 
.RI [ -d | --db ] 
.RI [ -l | --level ] 
.RI [ -h | --hilfe ] 
.RI [ suche ] 
.SH DESCRIPTION
Kommandozeilen Programm für MediathekView
.SH OPTIONS
.B \-h, \-\-hilfe
Uebersicht der Parameter.
.SH SEE ALSO
.BR /usr/lib/mtvclient/bin/mtv_web.py.
