#!/bin/bash
# --------------------------------------------------------------------------
# Mediathekview auf der Kommandozeile
#
# Dieses Skript installiert die Projektdateien
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/mtv_cli
#
# --------------------------------------------------------------------------

# --- defaults used during installation   ----------------------------------

MTV_CLI_USER="pi"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

PACKAGES="python3 python3-pip python3-bottle"
if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
  apt-get update
  apt-get -y install $PACKAGES
fi

pip3 show pick | grep -q Version || pip3 install pick

# --- install specific files   ----------------------------------------------

# save current configuration
rand="$RANDOM"
if [ -f /etc/mtv_cli.conf ]; then
  mv /etc/mtv_cli.conf /etc/mtv_cli.conf.$rand
fi
if [ -f /etc/mtv_sendinforc ]; then
  mv /etc/mtv_sendinforc /etc/mtv_sendinforc.$rand
fi

# copy lib (web) directories
cp -a $(dirname "$0")/../files/usr/local/lib/mtv_cli /usr/local/lib
chown -R root:root /usr/local/lib/mtv_cli

# for other files dirs should exist, so this works
for f in `find $(dirname "$0")/../files/ -not -path "*__pycache__*" -type f`; do
  cp -v "$f" "${f#*files}"
  chown root:root "${f#*files}"
done
chmod 755 /usr/local/bin/mtv_cli.py
chmod 755 /usr/local/bin/mtv_web.py
chmod 644 /etc/mtv_cli.conf
chmod 644 /etc/systemd/system/mtv_web.service

# restore old configuration
if [ -f /etc/mtv_cli.conf.$rand ]; then
  mv -f /etc/mtv_cli.conf    /etc/mtv_cli.conf.neu
  mv /etc/mtv_cli.conf.$rand /etc/mtv_cli.conf
  echo -e "\nNeue Version der Konfigurationsdatei: /etc/mtv_cli.conf.neu"
fi
if [ -f /etc/mtv_sendinforc.$rand ]; then
  mv -f /etc/mtv_sendinforc       /etc/mtv_sendinforc.neu
  mv -f /etc/mtv_sendinforc.$rand /etc/mtv_sendinforc
fi

# --- crontab-Einträge schreiben   ------------------------------------------

if [ ! -f /etc/cron.d/mtv_cli ]; then
let hour_a=23*$RANDOM/32767
let hour_d=hour_a+1
cat >/etc/cron.d/mtv_cli <<EOF
15 $hour_a   * * *   $MTV_CLI_USER /usr/local/bin/mtv_cli.py -A
#30 $hour_a   * * *  $MTV_CLI_USER /usr/local/bin/mtv_sendinfo
00 $hour_d   * * *  $MTV_CLI_USER /usr/local/bin/mtv_cli.py -D
EOF
  echo -e "\nBitte crontab-Einträge in /etc/cron.d/mtv_cli anpassen!"
fi

# --- Systemd-Service für mtv_web.py einrichten   ---------------------------

sed -i -e "/User=/s/=.*/=$MTV_CLI_USER/" /etc/systemd/system/mtv_web.service
systemctl enable mtv_web.service

echo -e "\nWebinterface mit 'sudo systemctl start mtv_web.service' starten!"
